// =====================================================================
// Cotton Eyed Joe - player dataset
// =====================================================================
//
// Each entry is one footballer and one "featured" spell at a club:
//   fromClub = the club they made their senior, PERMANENT move to the
//              featuredClub from ("Where did you come from?")
//   toClub   = the club they joined when the featured spell ended
//              ("Where did you go?")
//
// Adding a player = appending one object to this array. Nothing else to do.
//
// PHOTO RULE (photoNeutral):
//   Photos must give no clues: never a shot in the featuredClub's kit or
//   crest - prefer national-team or portrait shots. All photos are
//   freely-licensed Wikimedia Commons files served via Special:FilePath.
//   photoNeutral: true  = the image was checked and does NOT show the
//                         featured club's kit/crest; the game displays it.
//   photoNeutral: false = not yet audited (or no photo); the game shows a
//                         neutral initials placeholder instead. Flip to
//                         true only after eyeballing the image.
//
// SOURCING / VERIFICATION STATUS (2026-06):
//   Chains were compiled from well-documented transfer history and
//   cross-checked against Wikipedia-derived sources; the trickiest cases
//   (loan tangles, comebacks, very recent moves) were individually
//   re-verified online. Loan nuances are flagged in "note" fields - the
//   game treats the common permanent-transfer reading as correct.
//   See tools/ for the Wikidata SPARQL pipeline used to extend this file.
//
// altSpellings: accepted alternative answers, matched case- and
// accent-insensitively in addition to the canonical club name.
// =====================================================================

const PLAYERS = [
  {
    id: "thierry-henry",
    name: "Thierry Henry",
    category: "Premier League Legends",
    featuredClub: "Arsenal",
    fromClub: "Juventus",
    toClub: "Barcelona",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Thierry_Henry_Euro_2008.JPG?width=600", // France at Euro 2008
    photoNeutral: true,
    altSpellings: { fromClub: ["Juve","Juventus FC"], toClub: ["FC Barcelona","Barca","Barça"] },
  },
  {
    id: "eric-cantona",
    name: "Eric Cantona",
    category: "Premier League Legends",
    featuredClub: "Leeds United",
    fromClub: "Nîmes",
    toClub: "Manchester United",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["Nimes","Nîmes Olympique","Nimes Olympique"], toClub: ["Man United","Man Utd","Manchester Utd","MUFC"] },
    // note: Leeds move began as a loan from Nîmes in early 1992 before becoming permanent.
  },
  {
    id: "cristiano-ronaldo",
    name: "Cristiano Ronaldo",
    category: "Premier League Legends",
    featuredClub: "Manchester United",
    fromClub: "Sporting CP",
    toClub: "Real Madrid",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Cristiano_Ronaldo_2018_(4x5_cropped).jpg?width=600", // Portugal, 2018 World Cup
    photoNeutral: true,
    altSpellings: { fromClub: ["Sporting Lisbon","Sporting","Sporting Clube de Portugal"], toClub: ["Real Madrid CF"] },
    // note: First United spell (2003-2009).
  },
  {
    id: "ruud-van-nistelrooy",
    name: "Ruud van Nistelrooy",
    category: "Premier League Legends",
    featuredClub: "Manchester United",
    fromClub: "PSV Eindhoven",
    toClub: "Real Madrid",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["PSV"], toClub: ["Real Madrid CF"] },
  },
  {
    id: "didier-drogba",
    name: "Didier Drogba",
    category: "Premier League Legends",
    featuredClub: "Chelsea",
    fromClub: "Marseille",
    toClub: "Shanghai Shenhua",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Didier_Drogba_2013_(1).JPG?width=600", // Galatasaray era (2013), no Chelsea kit
    photoNeutral: true,
    altSpellings: { fromClub: ["Olympique de Marseille","Olympique Marseille","OM"], toClub: ["Shanghai"] },
    // note: First Chelsea spell (2004-2012).
  },
  {
    id: "fernando-torres",
    name: "Fernando Torres",
    category: "Premier League Legends",
    featuredClub: "Liverpool",
    fromClub: "Atlético Madrid",
    toClub: "Chelsea",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["Atletico Madrid","Atletico","Atleti","Atlético de Madrid"], toClub: ["Chelsea FC"] },
  },
  {
    id: "luis-suarez",
    name: "Luis Suárez",
    category: "Premier League Legends",
    featuredClub: "Liverpool",
    fromClub: "Ajax",
    toClub: "Barcelona",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["AFC Ajax","Ajax Amsterdam"], toClub: ["FC Barcelona","Barca","Barça"] },
  },
  {
    id: "gareth-bale",
    name: "Gareth Bale",
    category: "Premier League Legends",
    featuredClub: "Tottenham Hotspur",
    fromClub: "Southampton",
    toClub: "Real Madrid",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["Southampton FC","Saints"], toClub: ["Real Madrid CF"] },
  },
  {
    id: "robin-van-persie",
    name: "Robin van Persie",
    category: "Premier League Legends",
    featuredClub: "Arsenal",
    fromClub: "Feyenoord",
    toClub: "Manchester United",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["Feyenoord Rotterdam"], toClub: ["Man United","Man Utd","Manchester Utd","MUFC"] },
  },
  {
    id: "patrick-vieira",
    name: "Patrick Vieira",
    category: "Premier League Legends",
    featuredClub: "Arsenal",
    fromClub: "AC Milan",
    toClub: "Juventus",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["Milan"], toClub: ["Juve","Juventus FC"] },
  },
  {
    id: "carlos-tevez",
    name: "Carlos Tevez",
    category: "Premier League Legends",
    featuredClub: "Manchester United",
    fromClub: "West Ham United",
    toClub: "Manchester City",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["West Ham"], toClub: ["Man City","MCFC"] },
    // note: United spell was technically a two-year loan via third-party owners; the common reading (West Ham -> United -> City) is used.
  },
  {
    id: "alan-shearer",
    name: "Alan Shearer",
    category: "Premier League Legends",
    featuredClub: "Blackburn Rovers",
    fromClub: "Southampton",
    toClub: "Newcastle United",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["Southampton FC","Saints"], toClub: ["Newcastle","NUFC"] },
  },
  {
    id: "roy-keane",
    name: "Roy Keane",
    category: "Premier League Legends",
    featuredClub: "Manchester United",
    fromClub: "Nottingham Forest",
    toClub: "Celtic",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["Forest"], toClub: ["Celtic FC","Glasgow Celtic"] },
  },
  {
    id: "gianfranco-zola",
    name: "Gianfranco Zola",
    category: "Premier League Legends",
    featuredClub: "Chelsea",
    fromClub: "Parma",
    toClub: "Cagliari",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["Parma Calcio","AC Parma"], toClub: ["Cagliari Calcio"] },
  },
  {
    id: "peter-schmeichel",
    name: "Peter Schmeichel",
    category: "Premier League Legends",
    featuredClub: "Manchester United",
    fromClub: "Brøndby",
    toClub: "Sporting CP",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["Brondby","Brøndby IF","Brondby IF"], toClub: ["Sporting Lisbon","Sporting","Sporting Clube de Portugal"] },
  },
  {
    id: "jurgen-klinsmann",
    name: "Jürgen Klinsmann",
    category: "Premier League Legends",
    featuredClub: "Tottenham Hotspur",
    fromClub: "Monaco",
    toClub: "Bayern Munich",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["AS Monaco"], toClub: ["Bayern","FC Bayern","Bayern München","Bayern Munchen","FC Bayern Munich"] },
    // note: First Spurs spell (1994-95).
  },
  {
    id: "wayne-rooney",
    name: "Wayne Rooney",
    category: "Premier League Legends",
    featuredClub: "Manchester United",
    fromClub: "Everton",
    toClub: "Everton",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["Everton FC"], toClub: ["Everton FC"] },
    // note: Came from and returned to Everton - both answers are the same club.
  },
  {
    id: "luis-figo",
    name: "Luís Figo",
    category: "La Liga",
    featuredClub: "Real Madrid",
    fromClub: "Barcelona",
    toClub: "Inter Milan",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Luis_Figo-2009.jpg?width=600", // Post-retirement portrait (2009)
    photoNeutral: true,
    altSpellings: { fromClub: ["FC Barcelona","Barca","Barça"], toClub: ["Inter","Internazionale","FC Internazionale"] },
  },
  {
    id: "ronaldinho",
    name: "Ronaldinho",
    category: "La Liga",
    featuredClub: "Barcelona",
    fromClub: "Paris Saint-Germain",
    toClub: "AC Milan",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Ronaldinho_by_Vicario.JPG?width=600", // Kit not yet audited
    photoNeutral: false,
    altSpellings: { fromClub: ["PSG","Paris SG","Paris Saint Germain","Paris St-Germain","Paris St Germain"], toClub: ["Milan"] },
  },
  {
    id: "david-villa",
    name: "David Villa",
    category: "La Liga",
    featuredClub: "Barcelona",
    fromClub: "Valencia",
    toClub: "Atlético Madrid",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["Valencia CF"], toClub: ["Atletico Madrid","Atletico","Atleti","Atlético de Madrid"] },
  },
  {
    id: "xabi-alonso",
    name: "Xabi Alonso",
    category: "La Liga",
    featuredClub: "Real Madrid",
    fromClub: "Liverpool",
    toClub: "Bayern Munich",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["Liverpool FC"], toClub: ["Bayern","FC Bayern","Bayern München","Bayern Munchen","FC Bayern Munich"] },
  },
  {
    id: "neymar",
    name: "Neymar",
    category: "La Liga",
    featuredClub: "Barcelona",
    fromClub: "Santos",
    toClub: "Paris Saint-Germain",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Neymar_Junior_the_Future_of_Brazil.jpg?width=600", // Brazil-era shot, pre-Barcelona
    photoNeutral: true,
    altSpellings: { fromClub: ["Santos FC"], toClub: ["PSG","Paris SG","Paris Saint Germain","Paris St-Germain","Paris St Germain"] },
  },
  {
    id: "gonzalo-higuain",
    name: "Gonzalo Higuaín",
    category: "La Liga",
    featuredClub: "Real Madrid",
    fromClub: "River Plate",
    toClub: "Napoli",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["CA River Plate"], toClub: ["SSC Napoli"] },
  },
  {
    id: "angel-di-maria",
    name: "Ángel Di María",
    category: "La Liga",
    featuredClub: "Real Madrid",
    fromClub: "Benfica",
    toClub: "Manchester United",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["SL Benfica"], toClub: ["Man United","Man Utd","Manchester Utd","MUFC"] },
  },
  {
    id: "mesut-ozil",
    name: "Mesut Özil",
    category: "La Liga",
    featuredClub: "Real Madrid",
    fromClub: "Werder Bremen",
    toClub: "Arsenal",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["Bremen","SV Werder Bremen"], toClub: ["Arsenal FC","The Gunners"] },
  },
  {
    id: "antoine-griezmann",
    name: "Antoine Griezmann",
    category: "La Liga",
    featuredClub: "Atlético Madrid",
    fromClub: "Real Sociedad",
    toClub: "Barcelona",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["La Real","Sociedad"], toClub: ["FC Barcelona","Barca","Barça"] },
    // note: First Atlético spell (2014-2019).
  },
  {
    id: "diego-forlan",
    name: "Diego Forlán",
    category: "La Liga",
    featuredClub: "Atlético Madrid",
    fromClub: "Villarreal",
    toClub: "Inter Milan",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["Villarreal CF","Villareal"], toClub: ["Inter","Internazionale","FC Internazionale"] },
  },
  {
    id: "sergio-ramos",
    name: "Sergio Ramos",
    category: "La Liga",
    featuredClub: "Real Madrid",
    fromClub: "Sevilla",
    toClub: "Paris Saint-Germain",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["Sevilla FC","Seville"], toClub: ["PSG","Paris SG","Paris Saint Germain","Paris St-Germain","Paris St Germain"] },
  },
  {
    id: "dani-alves",
    name: "Dani Alves",
    category: "La Liga",
    featuredClub: "Barcelona",
    fromClub: "Sevilla",
    toClub: "Juventus",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["Sevilla FC","Seville"], toClub: ["Juve","Juventus FC"] },
    // note: First Barcelona spell (2008-2016).
  },
  {
    id: "ivan-rakitic",
    name: "Ivan Rakitić",
    category: "La Liga",
    featuredClub: "Barcelona",
    fromClub: "Sevilla",
    toClub: "Sevilla",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["Sevilla FC","Seville"], toClub: ["Sevilla FC","Seville"] },
    // note: Came from and returned to Sevilla - both answers are the same club.
  },
  {
    id: "samuel-etoo",
    name: "Samuel Eto'o",
    category: "La Liga",
    featuredClub: "Barcelona",
    fromClub: "Mallorca",
    toClub: "Inter Milan",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["RCD Mallorca","Real Mallorca"], toClub: ["Inter","Internazionale","FC Internazionale"] },
  },
  {
    id: "rivaldo",
    name: "Rivaldo",
    category: "La Liga",
    featuredClub: "Barcelona",
    fromClub: "Deportivo La Coruña",
    toClub: "AC Milan",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["Deportivo","Depor","Deportivo de La Coruna"], toClub: ["Milan"] },
  },
  {
    id: "karim-benzema",
    name: "Karim Benzema",
    category: "La Liga",
    featuredClub: "Real Madrid",
    fromClub: "Lyon",
    toClub: "Al-Ittihad",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["Olympique Lyonnais","OL"], toClub: ["Al Ittihad","Ittihad"] },
  },
  {
    id: "luka-modric",
    name: "Luka Modrić",
    category: "La Liga",
    featuredClub: "Real Madrid",
    fromClub: "Tottenham Hotspur",
    toClub: "AC Milan",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Luka_Modric_2018.png?width=600", // Croatia, 2018 World Cup
    photoNeutral: true,
    altSpellings: { fromClub: ["Tottenham","Spurs"], toClub: ["Milan"] },
    // note: Joined AC Milan on a free transfer in July 2025.
  },
  {
    id: "david-beckham",
    name: "David Beckham",
    category: "La Liga",
    featuredClub: "Real Madrid",
    fromClub: "Manchester United",
    toClub: "LA Galaxy",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/David_Beckham_2011.jpg?width=600", // Kit not yet audited (2011, Galaxy era)
    photoNeutral: false,
    altSpellings: { fromClub: ["Man United","Man Utd","Manchester Utd","MUFC"], toClub: ["Los Angeles Galaxy","Galaxy"] },
  },
  {
    id: "kaka",
    name: "Kaká",
    category: "Serie A",
    featuredClub: "AC Milan",
    fromClub: "São Paulo",
    toClub: "Real Madrid",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Ricardo_Izecson_dos_Santos_Leite_(Kak%C3%A1)_01.jpg?width=600", // Kit not yet audited
    photoNeutral: false,
    altSpellings: { fromClub: ["Sao Paulo","São Paulo FC","Sao Paulo FC"], toClub: ["Real Madrid CF"] },
    // note: First Milan spell (2003-2009).
  },
  {
    id: "andriy-shevchenko",
    name: "Andriy Shevchenko",
    category: "Serie A",
    featuredClub: "AC Milan",
    fromClub: "Dynamo Kyiv",
    toClub: "Chelsea",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Andriy_Shevchenko_Ukraine-Sweden_Euro_2012.JPG?width=600", // Ukraine at Euro 2012
    photoNeutral: true,
    altSpellings: { fromClub: ["Dynamo Kiev","Dinamo Kiev","Dinamo Kyiv"], toClub: ["Chelsea FC"] },
    // note: First Milan spell (1999-2006).
  },
  {
    id: "gabriel-batistuta",
    name: "Gabriel Batistuta",
    category: "Serie A",
    featuredClub: "Fiorentina",
    fromClub: "Boca Juniors",
    toClub: "Roma",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["Boca","CA Boca Juniors"], toClub: ["AS Roma"] },
  },
  {
    id: "hernan-crespo",
    name: "Hernán Crespo",
    category: "Serie A",
    featuredClub: "Parma",
    fromClub: "River Plate",
    toClub: "Lazio",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["CA River Plate"], toClub: ["SS Lazio"] },
    // note: The 2000 move to Lazio was a world-record transfer at the time.
  },
  {
    id: "christian-vieri",
    name: "Christian Vieri",
    category: "Serie A",
    featuredClub: "Inter Milan",
    fromClub: "Lazio",
    toClub: "AC Milan",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["SS Lazio"], toClub: ["Milan"] },
    // note: The 1999 move from Lazio was a world-record transfer at the time.
  },
  {
    id: "pavel-nedved",
    name: "Pavel Nedvěd",
    category: "Serie A",
    featuredClub: "Lazio",
    fromClub: "Sparta Prague",
    toClub: "Juventus",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["AC Sparta Prague","Sparta Praha"], toClub: ["Juve","Juventus FC"] },
  },
  {
    id: "zlatan-ibrahimovic",
    name: "Zlatan Ibrahimović",
    category: "Serie A",
    featuredClub: "Inter Milan",
    fromClub: "Juventus",
    toClub: "Barcelona",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Zlatan_Ibrahimovi%C4%87_Euro_2012_vs_France_01.jpg?width=600", // Sweden at Euro 2012
    photoNeutral: true,
    altSpellings: { fromClub: ["Juve","Juventus FC"], toClub: ["FC Barcelona","Barca","Barça"] },
  },
  {
    id: "lilian-thuram",
    name: "Lilian Thuram",
    category: "Serie A",
    featuredClub: "Parma",
    fromClub: "Monaco",
    toClub: "Juventus",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["AS Monaco"], toClub: ["Juve","Juventus FC"] },
  },
  {
    id: "alessandro-nesta",
    name: "Alessandro Nesta",
    category: "Serie A",
    featuredClub: "AC Milan",
    fromClub: "Lazio",
    toClub: "Montreal Impact",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["SS Lazio"], toClub: ["Montreal","CF Montreal","CF Montréal"] },
  },
  {
    id: "andrea-pirlo",
    name: "Andrea Pirlo",
    category: "Serie A",
    featuredClub: "AC Milan",
    fromClub: "Inter Milan",
    toClub: "Juventus",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["Inter","Internazionale","FC Internazionale"], toClub: ["Juve","Juventus FC"] },
    // note: Owned by Inter with Reggina/Brescia loans before the 2001 Milan move.
  },
  {
    id: "gianluigi-buffon",
    name: "Gianluigi Buffon",
    category: "Serie A",
    featuredClub: "Juventus",
    fromClub: "Parma",
    toClub: "Paris Saint-Germain",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Gianluigi_Buffon_Euro_2012_vs_England_03.JPG?width=600", // Italy at Euro 2012
    photoNeutral: true,
    altSpellings: { fromClub: ["Parma Calcio","AC Parma"], toClub: ["PSG","Paris SG","Paris Saint Germain","Paris St-Germain","Paris St Germain"] },
    // note: First Juventus spell (2001-2018).
  },
  {
    id: "paul-pogba",
    name: "Paul Pogba",
    category: "Serie A",
    featuredClub: "Juventus",
    fromClub: "Manchester United",
    toClub: "Manchester United",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["Man United","Man Utd","Manchester Utd","MUFC"], toClub: ["Man United","Man Utd","Manchester Utd","MUFC"] },
    // note: First Juventus spell (2012-2016); came from and returned to Manchester United.
  },
  {
    id: "edinson-cavani",
    name: "Edinson Cavani",
    category: "Serie A",
    featuredClub: "Napoli",
    fromClub: "Palermo",
    toClub: "Paris Saint-Germain",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["US Palermo"], toClub: ["PSG","Paris SG","Paris Saint Germain","Paris St-Germain","Paris St Germain"] },
    // note: Napoli move began as a 2010 loan-with-obligation from Palermo.
  },
  {
    id: "roberto-baggio",
    name: "Roberto Baggio",
    category: "Serie A",
    featuredClub: "Juventus",
    fromClub: "Fiorentina",
    toClub: "AC Milan",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["ACF Fiorentina"], toClub: ["Milan"] },
  },
  {
    id: "mauro-icardi",
    name: "Mauro Icardi",
    category: "Serie A",
    featuredClub: "Inter Milan",
    fromClub: "Sampdoria",
    toClub: "Paris Saint-Germain",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["UC Sampdoria"], toClub: ["PSG","Paris SG","Paris Saint Germain","Paris St-Germain","Paris St Germain"] },
    // note: PSG move began as a 2019 loan, made permanent in 2020.
  },
  {
    id: "dennis-bergkamp",
    name: "Dennis Bergkamp",
    category: "Serie A",
    featuredClub: "Inter Milan",
    fromClub: "Ajax",
    toClub: "Arsenal",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["AFC Ajax","Ajax Amsterdam"], toClub: ["Arsenal FC","The Gunners"] },
  },
  {
    id: "juan-sebastian-veron",
    name: "Juan Sebastián Verón",
    category: "Serie A",
    featuredClub: "Lazio",
    fromClub: "Parma",
    toClub: "Manchester United",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["Parma Calcio","AC Parma"], toClub: ["Man United","Man Utd","Manchester Utd","MUFC"] },
  },
  {
    id: "robert-lewandowski",
    name: "Robert Lewandowski",
    category: "Bundesliga",
    featuredClub: "Borussia Dortmund",
    fromClub: "Lech Poznań",
    toClub: "Bayern Munich",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Robert_Lewandowski_2018%2C_JAP-POL_(cropped).jpg?width=600", // Poland, 2018 World Cup
    photoNeutral: true,
    altSpellings: { fromClub: ["Lech Poznan"], toClub: ["Bayern","FC Bayern","Bayern München","Bayern Munchen","FC Bayern Munich"] },
  },
  {
    id: "mats-hummels",
    name: "Mats Hummels",
    category: "Bundesliga",
    featuredClub: "Borussia Dortmund",
    fromClub: "Bayern Munich",
    toClub: "Bayern Munich",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["Bayern","FC Bayern","Bayern München","Bayern Munchen","FC Bayern Munich"], toClub: ["Bayern","FC Bayern","Bayern München","Bayern Munchen","FC Bayern Munich"] },
    // note: First Dortmund spell began as a 2008 loan from Bayern, permanent in 2009; came from and returned to Bayern.
  },
  {
    id: "ousmane-dembele",
    name: "Ousmane Dembélé",
    category: "Bundesliga",
    featuredClub: "Borussia Dortmund",
    fromClub: "Rennes",
    toClub: "Barcelona",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["Stade Rennais"], toClub: ["FC Barcelona","Barca","Barça"] },
  },
  {
    id: "pierre-emerick-aubameyang",
    name: "Pierre-Emerick Aubameyang",
    category: "Bundesliga",
    featuredClub: "Borussia Dortmund",
    fromClub: "Saint-Étienne",
    toClub: "Arsenal",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["Saint-Etienne","St Etienne","AS Saint-Étienne","ASSE"], toClub: ["Arsenal FC","The Gunners"] },
  },
  {
    id: "jadon-sancho",
    name: "Jadon Sancho",
    category: "Bundesliga",
    featuredClub: "Borussia Dortmund",
    fromClub: "Manchester City",
    toClub: "Manchester United",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["Man City","MCFC"], toClub: ["Man United","Man Utd","Manchester Utd","MUFC"] },
    // note: First Dortmund spell (2017-2021).
  },
  {
    id: "arjen-robben",
    name: "Arjen Robben",
    category: "Bundesliga",
    featuredClub: "Bayern Munich",
    fromClub: "Real Madrid",
    toClub: "Groningen",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Arjen_Robben.JPG?width=600", // Kit not yet audited
    photoNeutral: false,
    altSpellings: { fromClub: ["Real Madrid CF"], toClub: ["FC Groningen"] },
    // note: Retired in 2019, then made a comeback with boyhood club Groningen in 2020.
  },
  {
    id: "franck-ribery",
    name: "Franck Ribéry",
    category: "Bundesliga",
    featuredClub: "Bayern Munich",
    fromClub: "Marseille",
    toClub: "Fiorentina",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["Olympique de Marseille","Olympique Marseille","OM"], toClub: ["ACF Fiorentina"] },
  },
  {
    id: "michael-ballack",
    name: "Michael Ballack",
    category: "Bundesliga",
    featuredClub: "Bayern Munich",
    fromClub: "Bayer Leverkusen",
    toClub: "Chelsea",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["Leverkusen","Bayer 04 Leverkusen"], toClub: ["Chelsea FC"] },
    // note: First Bayern spell (2002-2006).
  },
  {
    id: "lothar-matthaus",
    name: "Lothar Matthäus",
    category: "Bundesliga",
    featuredClub: "Bayern Munich",
    fromClub: "Borussia Mönchengladbach",
    toClub: "Inter Milan",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["Gladbach","Borussia Monchengladbach","Mönchengladbach","Monchengladbach"], toClub: ["Inter","Internazionale","FC Internazionale"] },
    // note: First Bayern spell (1984-1988).
  },
  {
    id: "kevin-de-bruyne",
    name: "Kevin De Bruyne",
    category: "Bundesliga",
    featuredClub: "Wolfsburg",
    fromClub: "Chelsea",
    toClub: "Manchester City",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Kevin_De_Bruyne_201807091.jpg?width=600", // Belgium, 2018 World Cup
    photoNeutral: true,
    altSpellings: { fromClub: ["Chelsea FC"], toClub: ["Man City","MCFC"] },
    // note: Earlier Werder Bremen spell was a loan from Chelsea.
  },
  {
    id: "naby-keita",
    name: "Naby Keïta",
    category: "Bundesliga",
    featuredClub: "RB Leipzig",
    fromClub: "Red Bull Salzburg",
    toClub: "Liverpool",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["RB Salzburg","Salzburg","FC Salzburg"], toClub: ["Liverpool FC"] },
  },
  {
    id: "timo-werner",
    name: "Timo Werner",
    category: "Bundesliga",
    featuredClub: "RB Leipzig",
    fromClub: "VfB Stuttgart",
    toClub: "Chelsea",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["Stuttgart"], toClub: ["Chelsea FC"] },
    // note: First Leipzig spell (2016-2020).
  },
  {
    id: "granit-xhaka",
    name: "Granit Xhaka",
    category: "Bundesliga",
    featuredClub: "Borussia Mönchengladbach",
    fromClub: "Basel",
    toClub: "Arsenal",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["FC Basel"], toClub: ["Arsenal FC","The Gunners"] },
  },
  {
    id: "edin-dzeko",
    name: "Edin Džeko",
    category: "Bundesliga",
    featuredClub: "Wolfsburg",
    fromClub: "Teplice",
    toClub: "Manchester City",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["FK Teplice"], toClub: ["Man City","MCFC"] },
  },
  {
    id: "roberto-firmino",
    name: "Roberto Firmino",
    category: "Bundesliga",
    featuredClub: "Hoffenheim",
    fromClub: "Figueirense",
    toClub: "Liverpool",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["Figueirense FC"], toClub: ["Liverpool FC"] },
  },
  {
    id: "son-heung-min",
    name: "Son Heung-min",
    category: "Bundesliga",
    featuredClub: "Bayer Leverkusen",
    fromClub: "Hamburger SV",
    toClub: "Tottenham Hotspur",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Son_Heung-min_2016.jpg?width=600", // Kit not yet audited (2016)
    photoNeutral: false,
    altSpellings: { fromClub: ["Hamburg","HSV"], toClub: ["Tottenham","Spurs"] },
  },
  {
    id: "arturo-vidal",
    name: "Arturo Vidal",
    category: "Bundesliga",
    featuredClub: "Bayern Munich",
    fromClub: "Juventus",
    toClub: "Barcelona",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["Juve","Juventus FC"], toClub: ["FC Barcelona","Barca","Barça"] },
  },
  {
    id: "diego-maradona",
    name: "Diego Maradona",
    category: "World Cup Icons",
    featuredClub: "Napoli",
    fromClub: "Barcelona",
    toClub: "Sevilla",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Diego_Maradona_Argentina_1986_cup_Azteca_Stadium.jpg?width=600", // Argentina, 1986 World Cup
    photoNeutral: true,
    altSpellings: { fromClub: ["FC Barcelona","Barca","Barça"], toClub: ["Sevilla FC","Seville"] },
  },
  {
    id: "zinedine-zidane",
    name: "Zinedine Zidane",
    category: "World Cup Icons",
    featuredClub: "Juventus",
    fromClub: "Bordeaux",
    toClub: "Real Madrid",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Zinedine_Zidane_(cropped).JPG?width=600", // Kit not yet audited
    photoNeutral: false,
    altSpellings: { fromClub: ["Girondins de Bordeaux","Girondins"], toClub: ["Real Madrid CF"] },
  },
  {
    id: "ronaldo-nazario",
    name: "Ronaldo",
    category: "World Cup Icons",
    featuredClub: "Inter Milan",
    fromClub: "Barcelona",
    toClub: "Real Madrid",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["FC Barcelona","Barca","Barça"], toClub: ["Real Madrid CF"] },
    // note: The original Brazilian Ronaldo (R9).
  },
  {
    id: "romario",
    name: "Romário",
    category: "World Cup Icons",
    featuredClub: "Barcelona",
    fromClub: "PSV Eindhoven",
    toClub: "Flamengo",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["PSV"], toClub: ["CR Flamengo"] },
  },
  {
    id: "fabio-cannavaro",
    name: "Fabio Cannavaro",
    category: "World Cup Icons",
    featuredClub: "Juventus",
    fromClub: "Inter Milan",
    toClub: "Real Madrid",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["Inter","Internazionale","FC Internazionale"], toClub: ["Real Madrid CF"] },
    // note: Juventus spell 2004-2006, ending after the 2006 World Cup win.
  },
  {
    id: "johan-cruyff",
    name: "Johan Cruyff",
    category: "World Cup Icons",
    featuredClub: "Barcelona",
    fromClub: "Ajax",
    toClub: "Los Angeles Aztecs",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["AFC Ajax","Ajax Amsterdam"], toClub: ["LA Aztecs"] },
    // note: First Barcelona spell (1973-1978).
  },
  {
    id: "michel-platini",
    name: "Michel Platini",
    category: "World Cup Icons",
    featuredClub: "Saint-Étienne",
    fromClub: "Nancy",
    toClub: "Juventus",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["AS Nancy","AS Nancy-Lorraine"], toClub: ["Juve","Juventus FC"] },
  },
  {
    id: "franz-beckenbauer",
    name: "Franz Beckenbauer",
    category: "World Cup Icons",
    featuredClub: "New York Cosmos",
    fromClub: "Bayern Munich",
    toClub: "Hamburger SV",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["Bayern","FC Bayern","Bayern München","Bayern Munchen","FC Bayern Munich"], toClub: ["Hamburg","HSV"] },
    // note: First Cosmos spell (1977-1980); returned to the Cosmos in 1983.
  },
  {
    id: "zico",
    name: "Zico",
    category: "World Cup Icons",
    featuredClub: "Udinese",
    fromClub: "Flamengo",
    toClub: "Flamengo",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["CR Flamengo"], toClub: ["CR Flamengo"] },
    // note: Came from and returned to Flamengo - both answers are the same club.
  },
  {
    id: "socrates",
    name: "Sócrates",
    category: "World Cup Icons",
    featuredClub: "Fiorentina",
    fromClub: "Corinthians",
    toClub: "Flamengo",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["SC Corinthians","Corinthians Paulista"], toClub: ["CR Flamengo"] },
  },
  {
    id: "hristo-stoichkov",
    name: "Hristo Stoichkov",
    category: "World Cup Icons",
    featuredClub: "Barcelona",
    fromClub: "CSKA Sofia",
    toClub: "Parma",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["CSKA"], toClub: ["Parma Calcio","AC Parma"] },
    // note: First Barcelona spell (1990-1995); returned to Barcelona in 1996.
  },
  {
    id: "gary-lineker",
    name: "Gary Lineker",
    category: "World Cup Icons",
    featuredClub: "Barcelona",
    fromClub: "Everton",
    toClub: "Tottenham Hotspur",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["Everton FC"], toClub: ["Tottenham","Spurs"] },
  },
  {
    id: "miroslav-klose",
    name: "Miroslav Klose",
    category: "World Cup Icons",
    featuredClub: "Bayern Munich",
    fromClub: "Werder Bremen",
    toClub: "Lazio",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["Bremen","SV Werder Bremen"], toClub: ["SS Lazio"] },
  },
  {
    id: "mario-gotze",
    name: "Mario Götze",
    category: "World Cup Icons",
    featuredClub: "Bayern Munich",
    fromClub: "Borussia Dortmund",
    toClub: "Borussia Dortmund",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["Dortmund","BVB"], toClub: ["Dortmund","BVB"] },
    // note: Bayern spell 2013-2016; came from and returned to Dortmund. Scored the 2014 World Cup final winner.
  },
  {
    id: "james-rodriguez",
    name: "James Rodríguez",
    category: "World Cup Icons",
    featuredClub: "Monaco",
    fromClub: "Porto",
    toClub: "Real Madrid",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["FC Porto"], toClub: ["Real Madrid CF"] },
    // note: 2014 World Cup Golden Boot winner; Real bought him straight after the tournament.
  },
  {
    id: "kylian-mbappe",
    name: "Kylian Mbappé",
    category: "World Cup Icons",
    featuredClub: "Paris Saint-Germain",
    fromClub: "Monaco",
    toClub: "Real Madrid",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Kylian_Mbapp%C3%A9_France.jpg?width=600", // France national team
    photoNeutral: true,
    altSpellings: { fromClub: ["AS Monaco"], toClub: ["Real Madrid CF"] },
    // note: PSG move began as a 2017 loan, made permanent in 2018.
  },
  {
    id: "jude-bellingham",
    name: "Jude Bellingham",
    category: "Modern Stars",
    featuredClub: "Borussia Dortmund",
    fromClub: "Birmingham City",
    toClub: "Real Madrid",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Jude_Bellingham_2022-11-21_1.jpg?width=600", // England, 2022 World Cup
    photoNeutral: true,
    altSpellings: { fromClub: ["Birmingham"], toClub: ["Real Madrid CF"] },
  },
  {
    id: "erling-haaland",
    name: "Erling Haaland",
    category: "Modern Stars",
    featuredClub: "Borussia Dortmund",
    fromClub: "Red Bull Salzburg",
    toClub: "Manchester City",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Erling_Haaland_June_2025.jpg?width=600", // Kit not yet audited (June 2025)
    photoNeutral: false,
    altSpellings: { fromClub: ["RB Salzburg","Salzburg","FC Salzburg"], toClub: ["Man City","MCFC"] },
  },
  {
    id: "victor-osimhen",
    name: "Victor Osimhen",
    category: "Modern Stars",
    featuredClub: "Lille",
    fromClub: "Charleroi",
    toClub: "Napoli",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["Sporting Charleroi","Royal Charleroi"], toClub: ["SSC Napoli"] },
    // note: Had an earlier Wolfsburg spell before Charleroi.
  },
  {
    id: "darwin-nunez",
    name: "Darwin Núñez",
    category: "Modern Stars",
    featuredClub: "Benfica",
    fromClub: "Almería",
    toClub: "Liverpool",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["Almeria","UD Almeria"], toClub: ["Liverpool FC"] },
  },
  {
    id: "alexis-mac-allister",
    name: "Alexis Mac Allister",
    category: "Modern Stars",
    featuredClub: "Brighton & Hove Albion",
    fromClub: "Argentinos Juniors",
    toClub: "Liverpool",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["Argentinos"], toClub: ["Liverpool FC"] },
    // note: Signed in January 2019 but loaned back to Argentinos Juniors (and Boca) before playing for Brighton.
  },
  {
    id: "moises-caicedo",
    name: "Moisés Caicedo",
    category: "Modern Stars",
    featuredClub: "Brighton & Hove Albion",
    fromClub: "Independiente del Valle",
    toClub: "Chelsea",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["IDV"], toClub: ["Chelsea FC"] },
  },
  {
    id: "josko-gvardiol",
    name: "Joško Gvardiol",
    category: "Modern Stars",
    featuredClub: "RB Leipzig",
    fromClub: "Dinamo Zagreb",
    toClub: "Manchester City",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["GNK Dinamo Zagreb","Dynamo Zagreb"], toClub: ["Man City","MCFC"] },
  },
  {
    id: "aurelien-tchouameni",
    name: "Aurélien Tchouaméni",
    category: "Modern Stars",
    featuredClub: "Monaco",
    fromClub: "Bordeaux",
    toClub: "Real Madrid",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["Girondins de Bordeaux","Girondins"], toClub: ["Real Madrid CF"] },
  },
  {
    id: "alexander-isak",
    name: "Alexander Isak",
    category: "Modern Stars",
    featuredClub: "Real Sociedad",
    fromClub: "Borussia Dortmund",
    toClub: "Newcastle United",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["Dortmund","BVB"], toClub: ["Newcastle","NUFC"] },
    // note: Willem II loan during the Sociedad spell; joined Liverpool from Newcastle in 2025.
  },
  {
    id: "bruno-fernandes",
    name: "Bruno Fernandes",
    category: "Modern Stars",
    featuredClub: "Sporting CP",
    fromClub: "Sampdoria",
    toClub: "Manchester United",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["UC Sampdoria"], toClub: ["Man United","Man Utd","Manchester Utd","MUFC"] },
  },
  {
    id: "casemiro",
    name: "Casemiro",
    category: "Modern Stars",
    featuredClub: "Real Madrid",
    fromClub: "São Paulo",
    toClub: "Manchester United",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["Sao Paulo","São Paulo FC","Sao Paulo FC"], toClub: ["Man United","Man Utd","Manchester Utd","MUFC"] },
    // note: Madrid move began as a 2013 loan from São Paulo; also had a Porto loan mid-spell.
  },
  {
    id: "rodri",
    name: "Rodri",
    category: "Modern Stars",
    featuredClub: "Atlético Madrid",
    fromClub: "Villarreal",
    toClub: "Manchester City",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["Villarreal CF","Villareal"], toClub: ["Man City","MCFC"] },
  },
  {
    id: "mohamed-salah",
    name: "Mohamed Salah",
    category: "Modern Stars",
    featuredClub: "Roma",
    fromClub: "Chelsea",
    toClub: "Liverpool",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Mohamed_Salah.JPG?width=600", // Kit not yet audited
    photoNeutral: false,
    altSpellings: { fromClub: ["Chelsea FC"], toClub: ["Liverpool FC"] },
    // note: Roma move began as a 2015 loan from Chelsea, made permanent in 2016.
  },
  {
    id: "dominik-szoboszlai",
    name: "Dominik Szoboszlai",
    category: "Modern Stars",
    featuredClub: "RB Leipzig",
    fromClub: "Red Bull Salzburg",
    toClub: "Liverpool",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["RB Salzburg","Salzburg","FC Salzburg"], toClub: ["Liverpool FC"] },
  },
  {
    id: "khvicha-kvaratskhelia",
    name: "Khvicha Kvaratskhelia",
    category: "Modern Stars",
    featuredClub: "Napoli",
    fromClub: "Dinamo Batumi",
    toClub: "Paris Saint-Germain",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["Dynamo Batumi"], toClub: ["PSG","Paris SG","Paris Saint Germain","Paris St-Germain","Paris St Germain"] },
    // note: Joined PSG in January 2025.
  },
  {
    id: "julian-alvarez",
    name: "Julián Álvarez",
    category: "Modern Stars",
    featuredClub: "Manchester City",
    fromClub: "River Plate",
    toClub: "Atlético Madrid",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["CA River Plate"], toClub: ["Atletico Madrid","Atletico","Atleti","Atlético de Madrid"] },
  },
  {
    id: "achraf-hakimi",
    name: "Achraf Hakimi",
    category: "Modern Stars",
    featuredClub: "Inter Milan",
    fromClub: "Real Madrid",
    toClub: "Paris Saint-Germain",
    photoUrl: null,
    photoNeutral: false,
    altSpellings: { fromClub: ["Real Madrid CF"], toClub: ["PSG","Paris SG","Paris Saint Germain","Paris St-Germain","Paris St Germain"] },
    // note: Dortmund spell was a loan from Real Madrid, so Inter signed him FROM Real Madrid in 2020.
  },
];
