// =====================================================================
// Cotton Eyed Joe - player dataset
// =====================================================================
//
// Each entry is one footballer and one "featured" spell at a club:
//   fromClub = the club they made their senior, PERMANENT move to the
//              featuredClub from ("Where did you come from?")
//   toClub   = the club they joined when the featured spell ended
//              ("Where did you go?")
//
// Adding a player = appending one object to this array. Nothing else to do.
//
// PHOTO RULE (photoNeutral):
//   Photos must give no clues: never a shot in the featuredClub's kit or
//   crest - prefer national-team or portrait shots. All photos are
//   freely-licensed Wikimedia Commons files served via Special:FilePath.
//   photoNeutral: true  = the image was checked and does NOT show the
//                         featured club's kit/crest; the game displays it.
//   photoNeutral: false = not yet audited (or no photo); the game shows a
//                         neutral initials placeholder instead. Flip to
//                         true only after eyeballing the image.
//
// SOURCING / VERIFICATION STATUS (2026-06):
//   Chains were compiled from well-documented transfer history and
//   cross-checked against Wikipedia-derived sources; the trickiest cases
//   (loan tangles, comebacks, very recent moves) were individually
//   re-verified online. Loan nuances are flagged in "note" fields - the
//   game treats the common permanent-transfer reading as correct.
//   See tools/ for the Wikidata SPARQL pipeline used to extend this file.
//
// altSpellings: accepted alternative answers, matched case- and
// accent-insensitively in addition to the canonical club name.
// =====================================================================

const PLAYERS = [
  {
    id: "thierry-henry",
    name: "Thierry Henry",
    category: "Premier League Legends",
    featuredClub: "Arsenal",
    fromClub: "Juventus",
    toClub: "Barcelona",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Thierry_Henry_Euro_2008.JPG?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["Juve","Juventus FC"], toClub: ["FC Barcelona","Barca","Barça"] },
  },
  {
    id: "eric-cantona",
    name: "Eric Cantona",
    category: "Premier League Legends",
    featuredClub: "Leeds United",
    fromClub: "Nîmes",
    toClub: "Manchester United",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Cantona_(20660481956).jpg?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["Nimes","Nîmes Olympique","Nimes Olympique"], toClub: ["Man United","Man Utd","Manchester Utd","MUFC"] },
  },
  {
    id: "cristiano-ronaldo",
    name: "Cristiano Ronaldo",
    category: "Premier League Legends",
    featuredClub: "Manchester United",
    fromClub: "Sporting CP",
    toClub: "Real Madrid",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Cristiano_Ronaldo_2018_(4x5_cropped).jpg?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["Sporting Lisbon","Sporting","Sporting Clube de Portugal"], toClub: ["Real Madrid CF"] },
  },
  {
    id: "ruud-van-nistelrooy",
    name: "Ruud van Nistelrooy",
    category: "Premier League Legends",
    featuredClub: "Manchester United",
    fromClub: "PSV Eindhoven",
    toClub: "Real Madrid",
    photoUrl: null,
    photoNeutral: true,
    wiki: "Ruud van Nistelrooy", // photo resolved at runtime from Wikipedia
    altSpellings: { fromClub: ["PSV"], toClub: ["Real Madrid CF"] },
  },
  {
    id: "didier-drogba",
    name: "Didier Drogba",
    category: "Premier League Legends",
    featuredClub: "Chelsea",
    fromClub: "Marseille",
    toClub: "Shanghai Shenhua",
    photoUrl: null,
    photoNeutral: true,
    wiki: "Didier Drogba", // photo resolved at runtime from Wikipedia
    altSpellings: { fromClub: ["Olympique de Marseille","Olympique Marseille","OM"], toClub: ["Shanghai"] },
  },
  {
    id: "fernando-torres",
    name: "Fernando Torres",
    category: "Premier League Legends",
    featuredClub: "Liverpool",
    fromClub: "Atlético Madrid",
    toClub: "Chelsea",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Adil_Rami_and_Fernando_Torres_Spain-France_Euro_2012.jpg?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["Atletico Madrid","Atletico","Atleti","Atlético de Madrid"], toClub: ["Chelsea FC"] },
  },
  {
    id: "luis-suarez",
    name: "Luis Suárez",
    category: "Premier League Legends",
    featuredClub: "Liverpool",
    fromClub: "Ajax",
    toClub: "Barcelona",
    photoUrl: null,
    photoNeutral: true,
    wiki: "Luis Suárez", // photo resolved at runtime from Wikipedia
    altSpellings: { fromClub: ["AFC Ajax","Ajax Amsterdam"], toClub: ["FC Barcelona","Barca","Barça"] },
  },
  {
    id: "gareth-bale",
    name: "Gareth Bale",
    category: "Premier League Legends",
    featuredClub: "Tottenham Hotspur",
    fromClub: "Southampton",
    toClub: "Real Madrid",
    photoUrl: null,
    photoNeutral: true,
    wiki: "Gareth Bale", // photo resolved at runtime from Wikipedia
    altSpellings: { fromClub: ["Southampton FC","Saints"], toClub: ["Real Madrid CF"] },
  },
  {
    id: "robin-van-persie",
    name: "Robin van Persie",
    category: "Premier League Legends",
    featuredClub: "Arsenal",
    fromClub: "Feyenoord",
    toClub: "Manchester United",
    photoUrl: null,
    photoNeutral: true,
    wiki: "Robin van Persie", // photo resolved at runtime from Wikipedia
    altSpellings: { fromClub: ["Feyenoord Rotterdam"], toClub: ["Man United","Man Utd","Manchester Utd","MUFC"] },
  },
  {
    id: "patrick-vieira",
    name: "Patrick Vieira",
    category: "Premier League Legends",
    featuredClub: "Arsenal",
    fromClub: "AC Milan",
    toClub: "Juventus",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Patrick_Vieira_NYCFC_(cropped).JPG?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["Milan"], toClub: ["Juve","Juventus FC"] },
  },
  {
    id: "carlos-tevez",
    name: "Carlos Tevez",
    category: "Premier League Legends",
    featuredClub: "Manchester United",
    fromClub: "West Ham United",
    toClub: "Manchester City",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Carlos_Tevez_with_Argentina_at_the_Boleyn_Ground_in_November_2014.jpg?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["West Ham"], toClub: ["Man City","MCFC"] },
  },
  {
    id: "alan-shearer",
    name: "Alan Shearer",
    category: "Premier League Legends",
    featuredClub: "Blackburn Rovers",
    fromClub: "Southampton",
    toClub: "Newcastle United",
    photoUrl: null,
    photoNeutral: true,
    wiki: "Alan Shearer", // photo resolved at runtime from Wikipedia
    altSpellings: { fromClub: ["Southampton FC","Saints"], toClub: ["Newcastle","NUFC"] },
  },
  {
    id: "roy-keane",
    name: "Roy Keane",
    category: "Premier League Legends",
    featuredClub: "Manchester United",
    fromClub: "Nottingham Forest",
    toClub: "Celtic",
    photoUrl: null,
    photoNeutral: true,
    wiki: "Roy Keane", // photo resolved at runtime from Wikipedia
    altSpellings: { fromClub: ["Forest"], toClub: ["Celtic FC","Glasgow Celtic"] },
  },
  {
    id: "gianfranco-zola",
    name: "Gianfranco Zola",
    category: "Premier League Legends",
    featuredClub: "Chelsea",
    fromClub: "Parma",
    toClub: "Cagliari",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Zola_at_Lazio.JPG?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["Parma Calcio","AC Parma"], toClub: ["Cagliari Calcio"] },
  },
  {
    id: "peter-schmeichel",
    name: "Peter Schmeichel",
    category: "Premier League Legends",
    featuredClub: "Manchester United",
    fromClub: "Brøndby",
    toClub: "Sporting CP",
    photoUrl: null,
    photoNeutral: true,
    wiki: "Peter Schmeichel", // photo resolved at runtime from Wikipedia
    altSpellings: { fromClub: ["Brondby","Brøndby IF","Brondby IF"], toClub: ["Sporting Lisbon","Sporting","Sporting Clube de Portugal"] },
  },
  {
    id: "jurgen-klinsmann",
    name: "Jürgen Klinsmann",
    category: "Premier League Legends",
    featuredClub: "Tottenham Hotspur",
    fromClub: "Monaco",
    toClub: "Bayern Munich",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Trainer_Klinsmann.JPG?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["AS Monaco"], toClub: ["Bayern","FC Bayern","Bayern München","Bayern Munchen","FC Bayern Munich"] },
  },
  {
    id: "wayne-rooney",
    name: "Wayne Rooney",
    category: "Premier League Legends",
    featuredClub: "Manchester United",
    fromClub: "Everton",
    toClub: "Everton",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Wayne_Rooney_(Broken_Foot).JPG?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["Everton FC"], toClub: ["Everton FC"] },
  },
  {
    id: "luis-figo",
    name: "Luís Figo",
    category: "La Liga",
    featuredClub: "Real Madrid",
    fromClub: "Barcelona",
    toClub: "Inter Milan",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Luis_Figo-2009.jpg?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["FC Barcelona","Barca","Barça"], toClub: ["Inter","Internazionale","FC Internazionale"] },
  },
  {
    id: "ronaldinho",
    name: "Ronaldinho",
    category: "La Liga",
    featuredClub: "Barcelona",
    fromClub: "Paris Saint-Germain",
    toClub: "AC Milan",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Ronaldinho_by_Vicario.JPG?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["PSG","Paris SG","Paris Saint Germain","Paris St-Germain","Paris St Germain"], toClub: ["Milan"] },
  },
  {
    id: "david-villa",
    name: "David Villa",
    category: "La Liga",
    featuredClub: "Barcelona",
    fromClub: "Valencia",
    toClub: "Atlético Madrid",
    photoUrl: null,
    photoNeutral: true,
    wiki: "David Villa", // photo resolved at runtime from Wikipedia
    altSpellings: { fromClub: ["Valencia CF"], toClub: ["Atletico Madrid","Atletico","Atleti","Atlético de Madrid"] },
  },
  {
    id: "xabi-alonso",
    name: "Xabi Alonso",
    category: "La Liga",
    featuredClub: "Real Madrid",
    fromClub: "Liverpool",
    toClub: "Bayern Munich",
    photoUrl: null,
    photoNeutral: true,
    wiki: "Xabi Alonso", // photo resolved at runtime from Wikipedia
    altSpellings: { fromClub: ["Liverpool FC"], toClub: ["Bayern","FC Bayern","Bayern München","Bayern Munchen","FC Bayern Munich"] },
  },
  {
    id: "neymar",
    name: "Neymar",
    category: "La Liga",
    featuredClub: "Barcelona",
    fromClub: "Santos",
    toClub: "Paris Saint-Germain",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Neymar_Junior_the_Future_of_Brazil.jpg?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["Santos FC"], toClub: ["PSG","Paris SG","Paris Saint Germain","Paris St-Germain","Paris St Germain"] },
  },
  {
    id: "gonzalo-higuain",
    name: "Gonzalo Higuaín",
    category: "La Liga",
    featuredClub: "Real Madrid",
    fromClub: "River Plate",
    toClub: "Napoli",
    photoUrl: null,
    photoNeutral: true,
    wiki: "Gonzalo Higuaín", // photo resolved at runtime from Wikipedia
    altSpellings: { fromClub: ["CA River Plate"], toClub: ["SSC Napoli"] },
  },
  {
    id: "angel-di-maria",
    name: "Ángel Di María",
    category: "La Liga",
    featuredClub: "Real Madrid",
    fromClub: "Benfica",
    toClub: "Manchester United",
    photoUrl: null,
    photoNeutral: true,
    wiki: "Ángel Di María", // photo resolved at runtime from Wikipedia
    altSpellings: { fromClub: ["SL Benfica"], toClub: ["Man United","Man Utd","Manchester Utd","MUFC"] },
  },
  {
    id: "mesut-ozil",
    name: "Mesut Özil",
    category: "La Liga",
    featuredClub: "Real Madrid",
    fromClub: "Werder Bremen",
    toClub: "Arsenal",
    photoUrl: null,
    photoNeutral: true,
    wiki: "Mesut Özil", // photo resolved at runtime from Wikipedia
    altSpellings: { fromClub: ["Bremen","SV Werder Bremen"], toClub: ["Arsenal FC","The Gunners"] },
  },
  {
    id: "antoine-griezmann",
    name: "Antoine Griezmann",
    category: "La Liga",
    featuredClub: "Atlético Madrid",
    fromClub: "Real Sociedad",
    toClub: "Barcelona",
    photoUrl: null,
    photoNeutral: true,
    wiki: "Antoine Griezmann", // photo resolved at runtime from Wikipedia
    altSpellings: { fromClub: ["La Real","Sociedad"], toClub: ["FC Barcelona","Barca","Barça"] },
  },
  {
    id: "diego-forlan",
    name: "Diego Forlán",
    category: "La Liga",
    featuredClub: "Atlético Madrid",
    fromClub: "Villarreal",
    toClub: "Inter Milan",
    photoUrl: null,
    photoNeutral: true,
    wiki: "Diego Forlán", // photo resolved at runtime from Wikipedia
    altSpellings: { fromClub: ["Villarreal CF","Villareal"], toClub: ["Inter","Internazionale","FC Internazionale"] },
  },
  {
    id: "sergio-ramos",
    name: "Sergio Ramos",
    category: "La Liga",
    featuredClub: "Real Madrid",
    fromClub: "Sevilla",
    toClub: "Paris Saint-Germain",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Sergio_Ramos_Euro_2012_vs_France_01.jpg?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["Sevilla FC","Seville"], toClub: ["PSG","Paris SG","Paris Saint Germain","Paris St-Germain","Paris St Germain"] },
  },
  {
    id: "dani-alves",
    name: "Dani Alves",
    category: "La Liga",
    featuredClub: "Barcelona",
    fromClub: "Sevilla",
    toClub: "Juventus",
    photoUrl: null,
    photoNeutral: true,
    wiki: "Dani Alves", // photo resolved at runtime from Wikipedia
    altSpellings: { fromClub: ["Sevilla FC","Seville"], toClub: ["Juve","Juventus FC"] },
  },
  {
    id: "ivan-rakitic",
    name: "Ivan Rakitić",
    category: "La Liga",
    featuredClub: "Barcelona",
    fromClub: "Sevilla",
    toClub: "Sevilla",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Ivan_Rakiti%C4%87_and_Dejan_Lovren_during_a_Croatia_training_session%2C_in_June_2018.jpg?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["Sevilla FC","Seville"], toClub: ["Sevilla FC","Seville"] },
  },
  {
    id: "samuel-etoo",
    name: "Samuel Eto'o",
    category: "La Liga",
    featuredClub: "Barcelona",
    fromClub: "Mallorca",
    toClub: "Inter Milan",
    photoUrl: null,
    photoNeutral: true,
    wiki: "Samuel Eto'o", // photo resolved at runtime from Wikipedia
    altSpellings: { fromClub: ["RCD Mallorca","Real Mallorca"], toClub: ["Inter","Internazionale","FC Internazionale"] },
  },
  {
    id: "rivaldo",
    name: "Rivaldo",
    category: "La Liga",
    featuredClub: "Barcelona",
    fromClub: "Deportivo La Coruña",
    toClub: "AC Milan",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Rivaldo.jpg?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["Deportivo","Depor","Deportivo de La Coruna"], toClub: ["Milan"] },
  },
  {
    id: "karim-benzema",
    name: "Karim Benzema",
    category: "La Liga",
    featuredClub: "Real Madrid",
    fromClub: "Lyon",
    toClub: "Al-Ittihad",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Karim_Benzema_Euro_2012.jpg?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["Olympique Lyonnais","OL"], toClub: ["Al Ittihad","Ittihad"] },
  },
  {
    id: "luka-modric",
    name: "Luka Modrić",
    category: "La Liga",
    featuredClub: "Real Madrid",
    fromClub: "Tottenham Hotspur",
    toClub: "AC Milan",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Luka_Modric_2018.png?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["Tottenham","Spurs"], toClub: ["Milan"] },
  },
  {
    id: "david-beckham",
    name: "David Beckham",
    category: "La Liga",
    featuredClub: "Real Madrid",
    fromClub: "Manchester United",
    toClub: "LA Galaxy",
    photoUrl: null,
    photoNeutral: true,
    wiki: "David Beckham", // photo resolved at runtime from Wikipedia
    altSpellings: { fromClub: ["Man United","Man Utd","Manchester Utd","MUFC"], toClub: ["Los Angeles Galaxy","Galaxy"] },
  },
  {
    id: "kaka",
    name: "Kaká",
    category: "Serie A",
    featuredClub: "AC Milan",
    fromClub: "São Paulo",
    toClub: "Real Madrid",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Ricardo_Izecson_dos_Santos_Leite_(Kak%C3%A1)_01.jpg?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["Sao Paulo","São Paulo FC","Sao Paulo FC"], toClub: ["Real Madrid CF"] },
  },
  {
    id: "andriy-shevchenko",
    name: "Andriy Shevchenko",
    category: "Serie A",
    featuredClub: "AC Milan",
    fromClub: "Dynamo Kyiv",
    toClub: "Chelsea",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Andriy_Shevchenko_Ukraine-Sweden_Euro_2012.JPG?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["Dynamo Kiev","Dinamo Kiev","Dinamo Kyiv"], toClub: ["Chelsea FC"] },
  },
  {
    id: "gabriel-batistuta",
    name: "Gabriel Batistuta",
    category: "Serie A",
    featuredClub: "Fiorentina",
    fromClub: "Boca Juniors",
    toClub: "Roma",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Gabriel_Batistuta_en_interview_avec_Florent_Torchut.jpg?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["Boca","CA Boca Juniors"], toClub: ["AS Roma"] },
  },
  {
    id: "hernan-crespo",
    name: "Hernán Crespo",
    category: "Serie A",
    featuredClub: "Parma",
    fromClub: "River Plate",
    toClub: "Lazio",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Chelsea_Legends_1_Inter_Forever_4_(42278922042).jpg?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["CA River Plate"], toClub: ["SS Lazio"] },
  },
  {
    id: "christian-vieri",
    name: "Christian Vieri",
    category: "Serie A",
    featuredClub: "Inter Milan",
    fromClub: "Lazio",
    toClub: "AC Milan",
    photoUrl: null,
    photoNeutral: true,
    wiki: "Christian Vieri", // photo resolved at runtime from Wikipedia
    altSpellings: { fromClub: ["SS Lazio"], toClub: ["Milan"] },
  },
  {
    id: "pavel-nedved",
    name: "Pavel Nedvěd",
    category: "Serie A",
    featuredClub: "Lazio",
    fromClub: "Sparta Prague",
    toClub: "Juventus",
    photoUrl: null,
    photoNeutral: true,
    wiki: "Pavel Nedvěd", // photo resolved at runtime from Wikipedia
    altSpellings: { fromClub: ["AC Sparta Prague","Sparta Praha"], toClub: ["Juve","Juventus FC"] },
  },
  {
    id: "zlatan-ibrahimovic",
    name: "Zlatan Ibrahimović",
    category: "Serie A",
    featuredClub: "Inter Milan",
    fromClub: "Juventus",
    toClub: "Barcelona",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Zlatan_Ibrahimovi%C4%87_Euro_2012_vs_France_01.jpg?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["Juve","Juventus FC"], toClub: ["FC Barcelona","Barca","Barça"] },
  },
  {
    id: "lilian-thuram",
    name: "Lilian Thuram",
    category: "Serie A",
    featuredClub: "Parma",
    fromClub: "Monaco",
    toClub: "Juventus",
    photoUrl: null,
    photoNeutral: true,
    wiki: "Lilian Thuram", // photo resolved at runtime from Wikipedia
    altSpellings: { fromClub: ["AS Monaco"], toClub: ["Juve","Juventus FC"] },
  },
  {
    id: "alessandro-nesta",
    name: "Alessandro Nesta",
    category: "Serie A",
    featuredClub: "AC Milan",
    fromClub: "Lazio",
    toClub: "Montreal Impact",
    photoUrl: null,
    photoNeutral: true,
    wiki: "Alessandro Nesta", // photo resolved at runtime from Wikipedia
    altSpellings: { fromClub: ["SS Lazio"], toClub: ["Montreal","CF Montreal","CF Montréal"] },
  },
  {
    id: "andrea-pirlo",
    name: "Andrea Pirlo",
    category: "Serie A",
    featuredClub: "AC Milan",
    fromClub: "Inter Milan",
    toClub: "Juventus",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Andrea_Pirlo_NYCFC.JPG?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["Inter","Internazionale","FC Internazionale"], toClub: ["Juve","Juventus FC"] },
  },
  {
    id: "gianluigi-buffon",
    name: "Gianluigi Buffon",
    category: "Serie A",
    featuredClub: "Juventus",
    fromClub: "Parma",
    toClub: "Paris Saint-Germain",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Gianluigi_Buffon_Euro_2012_vs_England_03.JPG?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["Parma Calcio","AC Parma"], toClub: ["PSG","Paris SG","Paris Saint Germain","Paris St-Germain","Paris St Germain"] },
  },
  {
    id: "paul-pogba",
    name: "Paul Pogba",
    category: "Serie A",
    featuredClub: "Juventus",
    fromClub: "Manchester United",
    toClub: "Manchester United",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Paul_Pogba_World_Cup_Trophy.jpg?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["Man United","Man Utd","Manchester Utd","MUFC"], toClub: ["Man United","Man Utd","Manchester Utd","MUFC"] },
  },
  {
    id: "edinson-cavani",
    name: "Edinson Cavani",
    category: "Serie A",
    featuredClub: "Napoli",
    fromClub: "Palermo",
    toClub: "Paris Saint-Germain",
    photoUrl: null,
    photoNeutral: true,
    wiki: "Edinson Cavani", // photo resolved at runtime from Wikipedia
    altSpellings: { fromClub: ["US Palermo"], toClub: ["PSG","Paris SG","Paris Saint Germain","Paris St-Germain","Paris St Germain"] },
  },
  {
    id: "roberto-baggio",
    name: "Roberto Baggio",
    category: "Serie A",
    featuredClub: "Juventus",
    fromClub: "Fiorentina",
    toClub: "AC Milan",
    photoUrl: null,
    photoNeutral: true,
    wiki: "Roberto Baggio", // photo resolved at runtime from Wikipedia
    altSpellings: { fromClub: ["ACF Fiorentina"], toClub: ["Milan"] },
  },
  {
    id: "mauro-icardi",
    name: "Mauro Icardi",
    category: "Serie A",
    featuredClub: "Inter Milan",
    fromClub: "Sampdoria",
    toClub: "Paris Saint-Germain",
    photoUrl: null,
    photoNeutral: true,
    wiki: "Mauro Icardi", // photo resolved at runtime from Wikipedia
    altSpellings: { fromClub: ["UC Sampdoria"], toClub: ["PSG","Paris SG","Paris Saint Germain","Paris St-Germain","Paris St Germain"] },
  },
  {
    id: "dennis-bergkamp",
    name: "Dennis Bergkamp",
    category: "Serie A",
    featuredClub: "Inter Milan",
    fromClub: "Ajax",
    toClub: "Arsenal",
    photoUrl: null,
    photoNeutral: true,
    wiki: "Dennis Bergkamp", // photo resolved at runtime from Wikipedia
    altSpellings: { fromClub: ["AFC Ajax","Ajax Amsterdam"], toClub: ["Arsenal FC","The Gunners"] },
  },
  {
    id: "juan-sebastian-veron",
    name: "Juan Sebastián Verón",
    category: "Serie A",
    featuredClub: "Lazio",
    fromClub: "Parma",
    toClub: "Manchester United",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Juan-Sebasti%C3%A1n-Ver%C3%B3n-EstudiantesLP-2013.JPG?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["Parma Calcio","AC Parma"], toClub: ["Man United","Man Utd","Manchester Utd","MUFC"] },
  },
  {
    id: "robert-lewandowski",
    name: "Robert Lewandowski",
    category: "Bundesliga",
    featuredClub: "Borussia Dortmund",
    fromClub: "Lech Poznań",
    toClub: "Bayern Munich",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Robert_Lewandowski_2018.jpg?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["Lech Poznan"], toClub: ["Bayern","FC Bayern","Bayern München","Bayern Munchen","FC Bayern Munich"] },
  },
  {
    id: "mats-hummels",
    name: "Mats Hummels",
    category: "Bundesliga",
    featuredClub: "Borussia Dortmund",
    fromClub: "Bayern Munich",
    toClub: "Bayern Munich",
    photoUrl: null,
    photoNeutral: true,
    wiki: "Mats Hummels", // photo resolved at runtime from Wikipedia
    altSpellings: { fromClub: ["Bayern","FC Bayern","Bayern München","Bayern Munchen","FC Bayern Munich"], toClub: ["Bayern","FC Bayern","Bayern München","Bayern Munchen","FC Bayern Munich"] },
  },
  {
    id: "ousmane-dembele",
    name: "Ousmane Dembélé",
    category: "Bundesliga",
    featuredClub: "Borussia Dortmund",
    fromClub: "Rennes",
    toClub: "Barcelona",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Ousmane_Demb%C3%A9l%C3%A9_World_Cup_Trophy.jpg?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["Stade Rennais"], toClub: ["FC Barcelona","Barca","Barça"] },
  },
  {
    id: "pierre-emerick-aubameyang",
    name: "Pierre-Emerick Aubameyang",
    category: "Bundesliga",
    featuredClub: "Borussia Dortmund",
    fromClub: "Saint-Étienne",
    toClub: "Arsenal",
    photoUrl: null,
    photoNeutral: true,
    wiki: "Pierre-Emerick Aubameyang", // photo resolved at runtime from Wikipedia
    altSpellings: { fromClub: ["Saint-Etienne","St Etienne","AS Saint-Étienne","ASSE"], toClub: ["Arsenal FC","The Gunners"] },
  },
  {
    id: "jadon-sancho",
    name: "Jadon Sancho",
    category: "Bundesliga",
    featuredClub: "Borussia Dortmund",
    fromClub: "Manchester City",
    toClub: "Manchester United",
    photoUrl: null,
    photoNeutral: true,
    wiki: "Jadon Sancho", // photo resolved at runtime from Wikipedia
    altSpellings: { fromClub: ["Man City","MCFC"], toClub: ["Man United","Man Utd","Manchester Utd","MUFC"] },
  },
  {
    id: "arjen-robben",
    name: "Arjen Robben",
    category: "Bundesliga",
    featuredClub: "Bayern Munich",
    fromClub: "Real Madrid",
    toClub: "Groningen",
    photoUrl: null,
    photoNeutral: true,
    wiki: "Arjen Robben", // photo resolved at runtime from Wikipedia
    altSpellings: { fromClub: ["Real Madrid CF"], toClub: ["FC Groningen"] },
  },
  {
    id: "franck-ribery",
    name: "Franck Ribéry",
    category: "Bundesliga",
    featuredClub: "Bayern Munich",
    fromClub: "Marseille",
    toClub: "Fiorentina",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Franck_Rib%C3%A9ry_20120611.jpg?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["Olympique de Marseille","Olympique Marseille","OM"], toClub: ["ACF Fiorentina"] },
  },
  {
    id: "michael-ballack",
    name: "Michael Ballack",
    category: "Bundesliga",
    featuredClub: "Bayern Munich",
    fromClub: "Bayer Leverkusen",
    toClub: "Chelsea",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Michael_Ballack_(Confed-Cup_2005).JPG?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["Leverkusen","Bayer 04 Leverkusen"], toClub: ["Chelsea FC"] },
  },
  {
    id: "lothar-matthaus",
    name: "Lothar Matthäus",
    category: "Bundesliga",
    featuredClub: "Bayern Munich",
    fromClub: "Borussia Mönchengladbach",
    toClub: "Inter Milan",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/6423_Lothar_Matth%C3%A4us.JPG?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["Gladbach","Borussia Monchengladbach","Mönchengladbach","Monchengladbach"], toClub: ["Inter","Internazionale","FC Internazionale"] },
  },
  {
    id: "kevin-de-bruyne",
    name: "Kevin De Bruyne",
    category: "Bundesliga",
    featuredClub: "Wolfsburg",
    fromClub: "Chelsea",
    toClub: "Manchester City",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Kevin_De_Bruyne_201807091.jpg?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["Chelsea FC"], toClub: ["Man City","MCFC"] },
  },
  {
    id: "naby-keita",
    name: "Naby Keïta",
    category: "Bundesliga",
    featuredClub: "RB Leipzig",
    fromClub: "Red Bull Salzburg",
    toClub: "Liverpool",
    photoUrl: null,
    photoNeutral: true,
    wiki: "Naby Keïta", // photo resolved at runtime from Wikipedia
    altSpellings: { fromClub: ["RB Salzburg","Salzburg","FC Salzburg"], toClub: ["Liverpool FC"] },
  },
  {
    id: "timo-werner",
    name: "Timo Werner",
    category: "Bundesliga",
    featuredClub: "RB Leipzig",
    fromClub: "VfB Stuttgart",
    toClub: "Chelsea",
    photoUrl: null,
    photoNeutral: true,
    wiki: "Timo Werner", // photo resolved at runtime from Wikipedia
    altSpellings: { fromClub: ["Stuttgart"], toClub: ["Chelsea FC"] },
  },
  {
    id: "granit-xhaka",
    name: "Granit Xhaka",
    category: "Bundesliga",
    featuredClub: "Borussia Mönchengladbach",
    fromClub: "Basel",
    toClub: "Arsenal",
    photoUrl: null,
    photoNeutral: true,
    wiki: "Granit Xhaka", // photo resolved at runtime from Wikipedia
    altSpellings: { fromClub: ["FC Basel"], toClub: ["Arsenal FC","The Gunners"] },
  },
  {
    id: "edin-dzeko",
    name: "Edin Džeko",
    category: "Bundesliga",
    featuredClub: "Wolfsburg",
    fromClub: "Teplice",
    toClub: "Manchester City",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Edin_Dzeko_at_Interview_(2020).png?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["FK Teplice"], toClub: ["Man City","MCFC"] },
  },
  {
    id: "roberto-firmino",
    name: "Roberto Firmino",
    category: "Bundesliga",
    featuredClub: "Hoffenheim",
    fromClub: "Figueirense",
    toClub: "Liverpool",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Roberto_Firmino_no_Al-Ahli_(cropped).png?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["Figueirense FC"], toClub: ["Liverpool FC"] },
  },
  {
    id: "son-heung-min",
    name: "Son Heung-min",
    category: "Bundesliga",
    featuredClub: "Bayer Leverkusen",
    fromClub: "Hamburger SV",
    toClub: "Tottenham Hotspur",
    photoUrl: null,
    photoNeutral: true,
    wiki: "Son Heung-min", // photo resolved at runtime from Wikipedia
    altSpellings: { fromClub: ["Hamburg","HSV"], toClub: ["Tottenham","Spurs"] },
  },
  {
    id: "arturo-vidal",
    name: "Arturo Vidal",
    category: "Bundesliga",
    featuredClub: "Bayern Munich",
    fromClub: "Juventus",
    toClub: "Barcelona",
    photoUrl: null,
    photoNeutral: true,
    wiki: "Arturo Vidal", // photo resolved at runtime from Wikipedia
    altSpellings: { fromClub: ["Juve","Juventus FC"], toClub: ["FC Barcelona","Barca","Barça"] },
  },
  {
    id: "diego-maradona",
    name: "Diego Maradona",
    category: "World Cup Icons",
    featuredClub: "Napoli",
    fromClub: "Barcelona",
    toClub: "Sevilla",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Diego_Maradona_Argentina_1986_cup_Azteca_Stadium.jpg?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["FC Barcelona","Barca","Barça"], toClub: ["Sevilla FC","Seville"] },
  },
  {
    id: "zinedine-zidane",
    name: "Zinedine Zidane",
    category: "World Cup Icons",
    featuredClub: "Juventus",
    fromClub: "Bordeaux",
    toClub: "Real Madrid",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Zinedine_zidane_wcf_2006-edit.jpg?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["Girondins de Bordeaux","Girondins"], toClub: ["Real Madrid CF"] },
  },
  {
    id: "ronaldo-nazario",
    name: "Ronaldo",
    category: "World Cup Icons",
    featuredClub: "Inter Milan",
    fromClub: "Barcelona",
    toClub: "Real Madrid",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Ronaldo_(brazil).JPG?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["FC Barcelona","Barca","Barça"], toClub: ["Real Madrid CF"] },
  },
  {
    id: "romario",
    name: "Romário",
    category: "World Cup Icons",
    featuredClub: "Barcelona",
    fromClub: "PSV Eindhoven",
    toClub: "Flamengo",
    photoUrl: null,
    photoNeutral: true,
    wiki: "Romário", // photo resolved at runtime from Wikipedia
    altSpellings: { fromClub: ["PSV"], toClub: ["CR Flamengo"] },
  },
  {
    id: "fabio-cannavaro",
    name: "Fabio Cannavaro",
    category: "World Cup Icons",
    featuredClub: "Juventus",
    fromClub: "Inter Milan",
    toClub: "Real Madrid",
    photoUrl: null,
    photoNeutral: true,
    wiki: "Fabio Cannavaro", // photo resolved at runtime from Wikipedia
    altSpellings: { fromClub: ["Inter","Internazionale","FC Internazionale"], toClub: ["Real Madrid CF"] },
  },
  {
    id: "johan-cruyff",
    name: "Johan Cruyff",
    category: "World Cup Icons",
    featuredClub: "Barcelona",
    fromClub: "Ajax",
    toClub: "Los Angeles Aztecs",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Johan_Cruijff_with_Chantal_1973.jpg?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["AFC Ajax","Ajax Amsterdam"], toClub: ["LA Aztecs"] },
  },
  {
    id: "michel-platini",
    name: "Michel Platini",
    category: "World Cup Icons",
    featuredClub: "Saint-Étienne",
    fromClub: "Nancy",
    toClub: "Juventus",
    photoUrl: null,
    photoNeutral: true,
    wiki: "Michel Platini", // photo resolved at runtime from Wikipedia
    altSpellings: { fromClub: ["AS Nancy","AS Nancy-Lorraine"], toClub: ["Juve","Juventus FC"] },
  },
  {
    id: "franz-beckenbauer",
    name: "Franz Beckenbauer",
    category: "World Cup Icons",
    featuredClub: "New York Cosmos",
    fromClub: "Bayern Munich",
    toClub: "Hamburger SV",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Franz_Beckenbauer.JPG?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["Bayern","FC Bayern","Bayern München","Bayern Munchen","FC Bayern Munich"], toClub: ["Hamburg","HSV"] },
  },
  {
    id: "zico",
    name: "Zico",
    category: "World Cup Icons",
    featuredClub: "Udinese",
    fromClub: "Flamengo",
    toClub: "Flamengo",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Zico.JPG?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["CR Flamengo"], toClub: ["CR Flamengo"] },
  },
  {
    id: "socrates",
    name: "Sócrates",
    category: "World Cup Icons",
    featuredClub: "Fiorentina",
    fromClub: "Corinthians",
    toClub: "Flamengo",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Socrates_(futebolista)_participando_do_movimento_pol%C3%ADtico_Diretas_J%C3%A1.jpg?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["SC Corinthians","Corinthians Paulista"], toClub: ["CR Flamengo"] },
  },
  {
    id: "hristo-stoichkov",
    name: "Hristo Stoichkov",
    category: "World Cup Icons",
    featuredClub: "Barcelona",
    fromClub: "CSKA Sofia",
    toClub: "Parma",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Stoichkov_in_2011.JPG?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["CSKA"], toClub: ["Parma Calcio","AC Parma"] },
  },
  {
    id: "gary-lineker",
    name: "Gary Lineker",
    category: "World Cup Icons",
    featuredClub: "Barcelona",
    fromClub: "Everton",
    toClub: "Tottenham Hotspur",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Gary_Lineker_(cropped).jpg?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["Everton FC"], toClub: ["Tottenham","Spurs"] },
  },
  {
    id: "miroslav-klose",
    name: "Miroslav Klose",
    category: "World Cup Icons",
    featuredClub: "Bayern Munich",
    fromClub: "Werder Bremen",
    toClub: "Lazio",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/FIFA_WC-qualification_2014_-_Austria_vs._Germany_2012-09-11_-_Miroslav_Klose_01.JPG?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["Bremen","SV Werder Bremen"], toClub: ["SS Lazio"] },
  },
  {
    id: "mario-gotze",
    name: "Mario Götze",
    category: "World Cup Icons",
    featuredClub: "Bayern Munich",
    fromClub: "Borussia Dortmund",
    toClub: "Borussia Dortmund",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/FIFA_WC-qualification_2014_-_Austria_vs._Germany_2012-09-11_-_Mario_G%C3%B6tze_01.JPG?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["Dortmund","BVB"], toClub: ["Dortmund","BVB"] },
  },
  {
    id: "james-rodriguez",
    name: "James Rodríguez",
    category: "World Cup Icons",
    featuredClub: "Monaco",
    fromClub: "Porto",
    toClub: "Real Madrid",
    photoUrl: null,
    photoNeutral: true,
    wiki: "James Rodríguez", // photo resolved at runtime from Wikipedia
    altSpellings: { fromClub: ["FC Porto"], toClub: ["Real Madrid CF"] },
  },
  {
    id: "kylian-mbappe",
    name: "Kylian Mbappé",
    category: "World Cup Icons",
    featuredClub: "Paris Saint-Germain",
    fromClub: "Monaco",
    toClub: "Real Madrid",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Kylian_Mbapp%C3%A9_France.jpg?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["AS Monaco"], toClub: ["Real Madrid CF"] },
  },
  {
    id: "jude-bellingham",
    name: "Jude Bellingham",
    category: "Modern Stars",
    featuredClub: "Borussia Dortmund",
    fromClub: "Birmingham City",
    toClub: "Real Madrid",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Jude_Bellingham_2022-11-21_1.jpg?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["Birmingham"], toClub: ["Real Madrid CF"] },
  },
  {
    id: "erling-haaland",
    name: "Erling Haaland",
    category: "Modern Stars",
    featuredClub: "Borussia Dortmund",
    fromClub: "Red Bull Salzburg",
    toClub: "Manchester City",
    photoUrl: null,
    photoNeutral: true,
    wiki: "Erling Haaland", // photo resolved at runtime from Wikipedia
    altSpellings: { fromClub: ["RB Salzburg","Salzburg","FC Salzburg"], toClub: ["Man City","MCFC"] },
  },
  {
    id: "victor-osimhen",
    name: "Victor Osimhen",
    category: "Modern Stars",
    featuredClub: "Lille",
    fromClub: "Charleroi",
    toClub: "Napoli",
    photoUrl: null,
    photoNeutral: true,
    wiki: "Victor Osimhen", // photo resolved at runtime from Wikipedia
    altSpellings: { fromClub: ["Sporting Charleroi","Royal Charleroi"], toClub: ["SSC Napoli"] },
  },
  {
    id: "darwin-nunez",
    name: "Darwin Núñez",
    category: "Modern Stars",
    featuredClub: "Benfica",
    fromClub: "Almería",
    toClub: "Liverpool",
    photoUrl: null,
    photoNeutral: true,
    wiki: "Darwin Núñez", // photo resolved at runtime from Wikipedia
    altSpellings: { fromClub: ["Almeria","UD Almeria"], toClub: ["Liverpool FC"] },
  },
  {
    id: "alexis-mac-allister",
    name: "Alexis Mac Allister",
    category: "Modern Stars",
    featuredClub: "Brighton & Hove Albion",
    fromClub: "Argentinos Juniors",
    toClub: "Liverpool",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Alexis_Mac_Allister_WC_2022.jpg?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["Argentinos"], toClub: ["Liverpool FC"] },
  },
  {
    id: "moises-caicedo",
    name: "Moisés Caicedo",
    category: "Modern Stars",
    featuredClub: "Brighton & Hove Albion",
    fromClub: "Independiente del Valle",
    toClub: "Chelsea",
    photoUrl: null,
    photoNeutral: true,
    wiki: "Moisés Caicedo", // photo resolved at runtime from Wikipedia
    altSpellings: { fromClub: ["IDV"], toClub: ["Chelsea FC"] },
  },
  {
    id: "josko-gvardiol",
    name: "Joško Gvardiol",
    category: "Modern Stars",
    featuredClub: "RB Leipzig",
    fromClub: "Dinamo Zagreb",
    toClub: "Manchester City",
    photoUrl: null,
    photoNeutral: true,
    wiki: "Joško Gvardiol", // photo resolved at runtime from Wikipedia
    altSpellings: { fromClub: ["GNK Dinamo Zagreb","Dynamo Zagreb"], toClub: ["Man City","MCFC"] },
  },
  {
    id: "aurelien-tchouameni",
    name: "Aurélien Tchouaméni",
    category: "Modern Stars",
    featuredClub: "Monaco",
    fromClub: "Bordeaux",
    toClub: "Real Madrid",
    photoUrl: null,
    photoNeutral: true,
    wiki: "Aurélien Tchouaméni", // photo resolved at runtime from Wikipedia
    altSpellings: { fromClub: ["Girondins de Bordeaux","Girondins"], toClub: ["Real Madrid CF"] },
  },
  {
    id: "alexander-isak",
    name: "Alexander Isak",
    category: "Modern Stars",
    featuredClub: "Real Sociedad",
    fromClub: "Borussia Dortmund",
    toClub: "Newcastle United",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/UEFA_EURO_qualifiers_Sweden_vs_Spain_20191015_Alexander_Isak_3.jpg?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["Dortmund","BVB"], toClub: ["Newcastle","NUFC"] },
  },
  {
    id: "bruno-fernandes",
    name: "Bruno Fernandes",
    category: "Modern Stars",
    featuredClub: "Sporting CP",
    fromClub: "Sampdoria",
    toClub: "Manchester United",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Bruno_Fernandes_Portugal%2C_2018.jpg?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["UC Sampdoria"], toClub: ["Man United","Man Utd","Manchester Utd","MUFC"] },
  },
  {
    id: "casemiro",
    name: "Casemiro",
    category: "Modern Stars",
    featuredClub: "Real Madrid",
    fromClub: "São Paulo",
    toClub: "Manchester United",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Casemiro.jpg?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["Sao Paulo","São Paulo FC","Sao Paulo FC"], toClub: ["Man United","Man Utd","Manchester Utd","MUFC"] },
  },
  {
    id: "rodri",
    name: "Rodri",
    category: "Modern Stars",
    featuredClub: "Atlético Madrid",
    fromClub: "Villarreal",
    toClub: "Manchester City",
    photoUrl: null,
    photoNeutral: true,
    wiki: "Rodri", // photo resolved at runtime from Wikipedia
    altSpellings: { fromClub: ["Villarreal CF","Villareal"], toClub: ["Man City","MCFC"] },
  },
  {
    id: "mohamed-salah",
    name: "Mohamed Salah",
    category: "Modern Stars",
    featuredClub: "Roma",
    fromClub: "Chelsea",
    toClub: "Liverpool",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Mohamed_Salah_Ghaly.jpg?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["Chelsea FC"], toClub: ["Liverpool FC"] },
  },
  {
    id: "dominik-szoboszlai",
    name: "Dominik Szoboszlai",
    category: "Modern Stars",
    featuredClub: "RB Leipzig",
    fromClub: "Red Bull Salzburg",
    toClub: "Liverpool",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Szoboszlaiirl.jpg?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["RB Salzburg","Salzburg","FC Salzburg"], toClub: ["Liverpool FC"] },
  },
  {
    id: "khvicha-kvaratskhelia",
    name: "Khvicha Kvaratskhelia",
    category: "Modern Stars",
    featuredClub: "Napoli",
    fromClub: "Dinamo Batumi",
    toClub: "Paris Saint-Germain",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Khvicha_Kvaratskhelia_2019.jpg?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["Dynamo Batumi"], toClub: ["PSG","Paris SG","Paris Saint Germain","Paris St-Germain","Paris St Germain"] },
  },
  {
    id: "julian-alvarez",
    name: "Julián Álvarez",
    category: "Modern Stars",
    featuredClub: "Manchester City",
    fromClub: "River Plate",
    toClub: "Atlético Madrid",
    photoUrl: null,
    photoNeutral: true,
    wiki: "Julián Álvarez", // photo resolved at runtime from Wikipedia
    altSpellings: { fromClub: ["CA River Plate"], toClub: ["Atletico Madrid","Atletico","Atleti","Atlético de Madrid"] },
  },
  {
    id: "achraf-hakimi",
    name: "Achraf Hakimi",
    category: "Modern Stars",
    featuredClub: "Inter Milan",
    fromClub: "Real Madrid",
    toClub: "Paris Saint-Germain",
    photoUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Iran-Morocco_by_soccer.ru_14_(Achraf_Hakimi).jpg?width=600",
    photoNeutral: true,
    altSpellings: { fromClub: ["Real Madrid CF"], toClub: ["PSG","Paris SG","Paris Saint Germain","Paris St-Germain","Paris St Germain"] },
  },
  {
    id: "leon-goretzka",
    name: "Leon Goretzka",
    category: "Modern Stars",
    featuredClub: "Schalke 04",
    fromClub: "VfL Bochum",
    toClub: "FC Bayern Munich",
    photoUrl: null,
    photoNeutral: false,
    wiki: "Leon Goretzka", // photo resolved at runtime from Wikipedia
    daily: "2026-06-15", // featured as the daily challenge on this date
    altSpellings: { fromClub: [], toClub: [] },
    // auto-added 2026-06-15 from Wikidata (unverified)
  },
  {
    id: "daniel-van-buyten",
    name: "Daniel Van Buyten",
    category: "Modern Stars",
    featuredClub: "Olympique de Marseille",
    fromClub: "Standard Liège",
    toClub: "Manchester City F.C.",
    photoUrl: null,
    photoNeutral: false,
    wiki: "Daniel Van Buyten", // photo resolved at runtime from Wikipedia
    daily: "2026-06-15", // featured as the daily challenge on this date
    altSpellings: { fromClub: [], toClub: [] },
    // auto-added 2026-06-15 from Wikidata (unverified)
  },
  {
    id: "leroy-sane",
    name: "Leroy Sané",
    category: "Modern Stars",
    featuredClub: "FC Bayern Munich",
    fromClub: "Manchester City F.C.",
    toClub: "Galatasaray S.K.",
    photoUrl: null,
    photoNeutral: false,
    wiki: "Leroy Sané", // photo resolved at runtime from Wikipedia
    daily: "2026-06-15", // featured as the daily challenge on this date
    altSpellings: { fromClub: [], toClub: [] },
    // auto-added 2026-06-15 from Wikidata (unverified)
  },
  {
    id: "alisson-becker",
    name: "Alisson Becker",
    category: "Modern Stars",
    featuredClub: "AS Roma",
    fromClub: "S.C. Internacional",
    toClub: "Liverpool F.C.",
    photoUrl: null,
    photoNeutral: false,
    wiki: "Alisson Becker", // photo resolved at runtime from Wikipedia
    daily: "2026-06-15", // featured as the daily challenge on this date
    altSpellings: { fromClub: [], toClub: [] },
    // auto-added 2026-06-15 from Wikidata (unverified)
  },
  {
    id: "atsushi-yanagisawa",
    name: "Atsushi Yanagisawa",
    category: "Modern Stars",
    featuredClub: "A.C.R. Messina",
    fromClub: "U.C. Sampdoria",
    toClub: "Kashima Antlers",
    photoUrl: null,
    photoNeutral: false,
    wiki: "Atsushi Yanagisawa", // photo resolved at runtime from Wikipedia
    daily: "2026-06-15", // featured as the daily challenge on this date
    altSpellings: { fromClub: [], toClub: [] },
    // auto-added 2026-06-15 from Wikidata (unverified)
  },
  {
    id: "emile-heskey",
    name: "Emile Heskey",
    category: "Premier League Legends",
    featuredClub: "Liverpool F.C.",
    fromClub: "Leicester City F.C.",
    toClub: "Birmingham City F.C.",
    photoUrl: null,
    photoNeutral: false,
    wiki: "Emile Heskey", // photo resolved at runtime from Wikipedia
    daily: "2026-06-15", // featured as the daily challenge on this date
    altSpellings: { fromClub: [], toClub: [] },
    // auto-added 2026-06-15 from Wikidata (unverified)
  },
  {
    id: "kazuma-watanabe",
    name: "Kazuma Watanabe",
    category: "Modern Stars",
    featuredClub: "Vissel Kobe",
    fromClub: "FC Tokyo",
    toClub: "Gamba Osaka",
    photoUrl: null,
    photoNeutral: false,
    wiki: "Kazuma Watanabe", // photo resolved at runtime from Wikipedia
    daily: "2026-06-15", // featured as the daily challenge on this date
    altSpellings: { fromClub: [], toClub: [] },
    // auto-added 2026-06-15 from Wikidata (unverified)
  },
  {
    id: "darijo-srna",
    name: "Darijo Srna",
    category: "Premier League Legends",
    featuredClub: "FC Shakhtar Donetsk",
    fromClub: "HNK Hajduk Split",
    toClub: "Cagliari Calcio",
    photoUrl: null,
    photoNeutral: false,
    wiki: "Darijo Srna", // photo resolved at runtime from Wikipedia
    daily: "2026-06-15", // featured as the daily challenge on this date
    altSpellings: { fromClub: [], toClub: [] },
    // auto-added 2026-06-15 from Wikidata (unverified)
  },
  {
    id: "hideaki-kitajima",
    name: "Hideaki Kitajima",
    category: "Modern Stars",
    featuredClub: "Kashiwa Reysol",
    fromClub: "Shimizu S-Pulse",
    toClub: "Roasso Kumamoto",
    photoUrl: null,
    photoNeutral: false,
    wiki: "Hideaki Kitajima", // photo resolved at runtime from Wikipedia
    daily: "2026-06-15", // featured as the daily challenge on this date
    altSpellings: { fromClub: [], toClub: [] },
    // auto-added 2026-06-15 from Wikidata (unverified)
  },
  {
    id: "javier-mascherano",
    name: "Javier Mascherano",
    category: "La Liga",
    featuredClub: "Fc Barcelona",
    fromClub: "Liverpool F.C.",
    toClub: "Hebei F.C.",
    photoUrl: null,
    photoNeutral: false,
    wiki: "Javier Mascherano", // photo resolved at runtime from Wikipedia
    daily: "2026-06-15", // featured as the daily challenge on this date
    altSpellings: { fromClub: [], toClub: [] },
    // auto-added 2026-06-15 from Wikidata (unverified)
  },
  {
    id: "blaise-matuidi",
    name: "Blaise Matuidi",
    category: "Modern Stars",
    featuredClub: "Paris Saint-Germain FC",
    fromClub: "AS Saint-Étienne",
    toClub: "Juventus FC",
    photoUrl: null,
    photoNeutral: false,
    wiki: "Blaise Matuidi", // photo resolved at runtime from Wikipedia
    daily: "2026-06-16", // featured as the daily challenge on this date
    altSpellings: { fromClub: [], toClub: [] },
    // auto-added 2026-06-16 from Wikidata (unverified)
  },
  {
    id: "gennaro-gattuso",
    name: "Gennaro Gattuso",
    category: "Modern Stars",
    featuredClub: "AC Milan",
    fromClub: "U.S. Salernitana 1919",
    toClub: "FC Sion",
    photoUrl: null,
    photoNeutral: false,
    wiki: "Gennaro Gattuso", // photo resolved at runtime from Wikipedia
    daily: "2026-06-16", // featured as the daily challenge on this date
    altSpellings: { fromClub: [], toClub: [] },
    // auto-added 2026-06-16 from Wikidata (unverified)
  },
  {
    id: "karl-heinz-rummenigge",
    name: "Karl-Heinz Rummenigge",
    category: "Modern Stars",
    featuredClub: "Inter Milan",
    fromClub: "FC Bayern Munich",
    toClub: "Servette FC",
    photoUrl: null,
    photoNeutral: false,
    wiki: "Karl-Heinz Rummenigge", // photo resolved at runtime from Wikipedia
    daily: "2026-06-16", // featured as the daily challenge on this date
    altSpellings: { fromClub: [], toClub: [] },
    // auto-added 2026-06-16 from Wikidata (unverified)
  },
  {
    id: "ashley-young",
    name: "Ashley Young",
    category: "Premier League Legends",
    featuredClub: "Manchester United F.C.",
    fromClub: "Aston Villa F.C.",
    toClub: "Inter Milan",
    photoUrl: null,
    photoNeutral: false,
    wiki: "Ashley Young", // photo resolved at runtime from Wikipedia
    daily: "2026-06-16", // featured as the daily challenge on this date
    altSpellings: { fromClub: [], toClub: [] },
    // auto-added 2026-06-16 from Wikidata (unverified)
  },
  {
    id: "didi",
    name: "Didi",
    category: "Modern Stars",
    featuredClub: "Fluminense F.C.",
    fromClub: "Madureira Esporte Clube",
    toClub: "Botafogo F.R.",
    photoUrl: null,
    photoNeutral: false,
    wiki: "Didi", // photo resolved at runtime from Wikipedia
    daily: "2026-06-16", // featured as the daily challenge on this date
    altSpellings: { fromClub: [], toClub: [] },
    // auto-added 2026-06-16 from Wikidata (unverified)
  },
  {
    id: "gheorghe-hagi",
    name: "Gheorghe Hagi",
    category: "Modern Stars",
    featuredClub: "FC Sportul Studențesc București",
    fromClub: "SSC Farul Constanța",
    toClub: "FCSB",
    photoUrl: null,
    photoNeutral: false,
    wiki: "Gheorghe Hagi", // photo resolved at runtime from Wikipedia
    daily: "2026-06-16", // featured as the daily challenge on this date
    altSpellings: { fromClub: [], toClub: [] },
    // auto-added 2026-06-16 from Wikidata (unverified)
  },
  {
    id: "lukas-podolski",
    name: "Lukas Podolski",
    category: "Modern Stars",
    featuredClub: "FC Bayern Munich",
    fromClub: "1. FC Köln",
    toClub: "1. FC Köln",
    photoUrl: null,
    photoNeutral: false,
    wiki: "Lukas Podolski", // photo resolved at runtime from Wikipedia
    daily: "2026-06-16", // featured as the daily challenge on this date
    altSpellings: { fromClub: [], toClub: [] },
    // auto-added 2026-06-16 from Wikidata (unverified)
  },
  {
    id: "kim-yong-sik",
    name: "Kim Yong-sik",
    category: "Modern Stars",
    featuredClub: "Pyongyang FC",
    fromClub: "Gyeongseong FC",
    toClub: "Gyeongseong FC",
    photoUrl: null,
    photoNeutral: false,
    wiki: "Kim Yong-sik", // photo resolved at runtime from Wikipedia
    daily: "2026-06-16", // featured as the daily challenge on this date
    altSpellings: { fromClub: [], toClub: [] },
    // auto-added 2026-06-16 from Wikidata (unverified)
  },
  {
    id: "daigo-nishi",
    name: "Daigo Nishi",
    category: "Modern Stars",
    featuredClub: "Kashima Antlers",
    fromClub: "Albirex Niigata",
    toClub: "Vissel Kobe",
    photoUrl: null,
    photoNeutral: false,
    wiki: "Daigo Nishi", // photo resolved at runtime from Wikipedia
    daily: "2026-06-16", // featured as the daily challenge on this date
    altSpellings: { fromClub: [], toClub: [] },
    // auto-added 2026-06-16 from Wikidata (unverified)
  },
  {
    id: "denis-law",
    name: "Denis Law",
    category: "Premier League Legends",
    featuredClub: "Manchester United F.C.",
    fromClub: "Torino FC",
    toClub: "Manchester City F.C.",
    photoUrl: null,
    photoNeutral: false,
    wiki: "Denis Law", // photo resolved at runtime from Wikipedia
    daily: "2026-06-16", // featured as the daily challenge on this date
    altSpellings: { fromClub: [], toClub: [] },
    // auto-added 2026-06-16 from Wikidata (unverified)
  },
  {
    id: "alexia-putellas",
    name: "Alexia Putellas",
    category: "Modern Stars",
    featuredClub: "Levante UD Women",
    fromClub: "RCD Espanyol Femenino",
    toClub: "FC Barcelona Femení",
    photoUrl: null,
    photoNeutral: false,
    wiki: "Alexia Putellas", // photo resolved at runtime from Wikipedia
    daily: "2026-06-17", // featured as the daily challenge on this date
    altSpellings: { fromClub: [], toClub: [] },
    // auto-added 2026-06-17 from Wikidata (unverified)
  },
  {
    id: "alex-oxlade-chamberlain",
    name: "Alex Oxlade-Chamberlain",
    category: "Premier League Legends",
    featuredClub: "Arsenal F.C.",
    fromClub: "Southampton F.C.",
    toClub: "Liverpool F.C.",
    photoUrl: null,
    photoNeutral: false,
    wiki: "Alex Oxlade-Chamberlain", // photo resolved at runtime from Wikipedia
    daily: "2026-06-17", // featured as the daily challenge on this date
    altSpellings: { fromClub: [], toClub: [] },
    // auto-added 2026-06-17 from Wikidata (unverified)
  },
  {
    id: "dino-zoff",
    name: "Dino Zoff",
    category: "Modern Stars",
    featuredClub: "SSC Napoli",
    fromClub: "Mantova 1911",
    toClub: "Juventus FC",
    photoUrl: null,
    photoNeutral: false,
    wiki: "Dino Zoff", // photo resolved at runtime from Wikipedia
    daily: "2026-06-17", // featured as the daily challenge on this date
    altSpellings: { fromClub: [], toClub: [] },
    // auto-added 2026-06-17 from Wikidata (unverified)
  },
  {
    id: "johan-neeskens",
    name: "Johan Neeskens",
    category: "La Liga",
    featuredClub: "Fc Barcelona",
    fromClub: "AFC Ajax",
    toClub: "New York Cosmos",
    photoUrl: null,
    photoNeutral: false,
    wiki: "Johan Neeskens", // photo resolved at runtime from Wikipedia
    daily: "2026-06-17", // featured as the daily challenge on this date
    altSpellings: { fromClub: [], toClub: [] },
    // auto-added 2026-06-17 from Wikidata (unverified)
  },
  {
    id: "atsuto-uchida",
    name: "Atsuto Uchida",
    category: "Modern Stars",
    featuredClub: "Schalke 04",
    fromClub: "Kashima Antlers",
    toClub: "1. FC Union Berlin",
    photoUrl: null,
    photoNeutral: false,
    wiki: "Atsuto Uchida", // photo resolved at runtime from Wikipedia
    daily: "2026-06-17", // featured as the daily challenge on this date
    altSpellings: { fromClub: [], toClub: [] },
    // auto-added 2026-06-17 from Wikidata (unverified)
  },
  {
    id: "marcelo-bielsa",
    name: "Marcelo Bielsa",
    category: "La Liga",
    featuredClub: "Club Sport Emelec",
    fromClub: "Newell's Old Boys",
    toClub: "Argentino de Rosario",
    photoUrl: null,
    photoNeutral: false,
    wiki: "Marcelo Bielsa", // photo resolved at runtime from Wikipedia
    daily: "2026-06-17", // featured as the daily challenge on this date
    altSpellings: { fromClub: [], toClub: [] },
    // auto-added 2026-06-17 from Wikidata (unverified)
  },
  {
    id: "lucas-biglia",
    name: "Lucas Biglia",
    category: "Modern Stars",
    featuredClub: "R.S.C. Anderlecht",
    fromClub: "Club Atlético Independiente",
    toClub: "SS Lazio",
    photoUrl: null,
    photoNeutral: false,
    wiki: "Lucas Biglia", // photo resolved at runtime from Wikipedia
    daily: "2026-06-17", // featured as the daily challenge on this date
    altSpellings: { fromClub: [], toClub: [] },
    // auto-added 2026-06-17 from Wikidata (unverified)
  },
  {
    id: "gojko-kacar",
    name: "Gojko Kačar",
    category: "Modern Stars",
    featuredClub: "Hamburger SV",
    fromClub: "Hertha BSC",
    toClub: "Cerezo Osaka",
    photoUrl: null,
    photoNeutral: false,
    wiki: "Gojko Kačar", // photo resolved at runtime from Wikipedia
    daily: "2026-06-17", // featured as the daily challenge on this date
    altSpellings: { fromClub: [], toClub: [] },
    // auto-added 2026-06-17 from Wikidata (unverified)
  },
  {
    id: "kai-havertz",
    name: "Kai Havertz",
    category: "Premier League Legends",
    featuredClub: "Chelsea F.C.",
    fromClub: "Bayer 04 Leverkusen",
    toClub: "Arsenal F.C.",
    photoUrl: null,
    photoNeutral: false,
    wiki: "Kai Havertz", // photo resolved at runtime from Wikipedia
    daily: "2026-06-17", // featured as the daily challenge on this date
    altSpellings: { fromClub: [], toClub: [] },
    // auto-added 2026-06-17 from Wikidata (unverified)
  },
  {
    id: "giuseppe-meazza",
    name: "Giuseppe Meazza",
    category: "Modern Stars",
    featuredClub: "AC Milan",
    fromClub: "Inter Milan",
    toClub: "Juventus FC",
    photoUrl: null,
    photoNeutral: false,
    wiki: "Giuseppe Meazza", // photo resolved at runtime from Wikipedia
    daily: "2026-06-17", // featured as the daily challenge on this date
    altSpellings: { fromClub: [], toClub: [] },
    // auto-added 2026-06-17 from Wikidata (unverified)
  },
];
